### ISSUE TITLE
准备界面识别不出，无法自动准备

### ISSUE THREAD

**Issue by FineTortinita** [AshenOneYe/WFHelper#1]
发现铃铛，点击
发现铃铛，点击
点击参加按钮
点击继续
点击继续
点击继续
点击继续
离开房间
离开房间
发现铃铛，点击
发现铃铛，点击
点击参加按钮
点击继续
点击继续
点击继续
点击继续
离开房间
离开房间
发现铃铛，点击
点击参加按钮
点击继续
点击继续
点击继续
点击继续
离开房间
离开房间
---------------------------
蓝叠64，mulator1440x810默认config

**Comment by AshenOneYe** [comment]
这个问题我也遇到过，即使是相同的模拟器，在不同电脑上运行也会有一些像素的区别，如果遇到某个图片无法识别的话还是得在自己的模拟器上进行截图然后替换配置文件中预设的截图文件，比如说你现在遇到的问题，可以先进到房间，然后使用python .\main.py -s configs\emulator1440x810\zhunbei.png进行截图。完成之后再重新开脚本就可以了。

**Comment by FineTortinita** [comment]
> 这个问题我也遇到过，即使是相同的模拟器，在不同电脑上运行也会有一些像素的区别，如果遇到某个图片无法识别的话还是得在自己的模拟器上进行截图然后替换配置文件中预设的截图文件，比如说你现在遇到的问题，可以先进到房间，然后使用python .\main.py -s configs\emulator1440x810\zhunbei.png进行截图。完成之后再重新开脚本就可以了。
重新截了个图好了，感谢~

**Comment by AshenOneYe** [comment]
还有你使用的脚本时release里下载的吗？那个版本是一天前的了，我也忘了是不是有什么bug，总之我还在同步更新，增加新功能，直接点code->download zip应该是最新版本，但是readme没有更新所以有些地方可能和readme里面描述的不一样，但是应该会比较稳定，有任何问题欢迎加群反馈，QQ群：340298463
