### ISSUE TITLE
关于QQ群的咨询

### ISSUE THREAD

**Issue by KisAaki** [AshenOneYe/WFHelper#59]
您好，在 readme 中看到了有关问题可以在群中咨询，但是翻来翻去也没找见QQ群，可以麻烦指个路么（

**Comment by KisAaki** [comment]
另外在使用的过程中还有个问题，个人尝试了blue stack 5,blue stack 4（国际版和国服版本）在使用EXE中的配置【0】时，可以识别铃铛但却无法进行点击操作（显示:error），同样也尝试了夜神模拟器（配置【1】），和上述错误相同（分辨率和DPI均设置正确）。目前能够正常运行的模拟器为雷神模拟器。

**Comment by AshenOneYe** [comment]
由于本人最近学业繁忙，此项目除配置文件有第三方热心人士在维护以外，其他部分我已经很少在维护了，所以QQ群暂时不收人了。对于第二个问题，bluestack不清楚，夜神估计是因为adb的原因，夜神的标新立异自己搞了个adb，会把我的adb杀掉，所以要用我的adb覆盖掉夜神自带的adb才行

**Comment by KisAaki** [comment]
明白了，对于蓝叠4和5均使用配置【0】和【1】测试过，我也没找见问题在哪里 :(

**Comment by AshenOneYe** [comment]
蓝叠我没用过，根据之前群友遇到问题的解决方法，应该是要在设置里开启允许adb连接
