### ISSUE TITLE
关于脚本多开的问题

### ISSUE THREAD

**Issue by dreamMilk** [AshenOneYe/WFHelper#85]
不知道脚本是否有控制多个模拟器（或同一模拟器多开）的功能实现。
目前我将脚本复制两份，分别控制一个模拟器，发现只有一个脚本在运行，另一个没有反应，但是正常启动，就像没有识别到任何图像一样，脚本后台的屏幕选项卡也是显示的被控模拟器的画面。
希望知道存在什么问题🙏

**Comment by AshenOneYe** [comment]
双开目前支持情况不太好，现在后台管理页面没法同时控制两个模拟器，所以开两个脚本意味着要开两个后台，但是后台的端口是写死的，所以开第二个的时候端口冲突了，有能力的话可以改下源码里的服务器默认端口

**Comment by dreamMilk** [comment]
> 双开目前支持情况不太好，现在后台管理页面没法同时控制两个模拟器，所以开两个脚本意味着要开两个后台，但是后台的端口是写死的，所以开第二个的时候端口冲突了，有能力的话可以改下源码里的服务器默认端口

后台端口我修改了，不然就卡在启动的时候了
双开脚本各自的后台都可以正常打开，并且后台屏幕选项卡中的画面也是其控制的模拟器的画面，应该说明脚本与模拟器之间的连接没有错乱，脚本运行也没有问题，一个脚本正常工作识图点击，另一个就是毫无动作在10分钟后开始一直提示长时间未操作，随机点击。
不知道问题在什么地方，难道是什么资源被抢占了另一个动不了🤔

**Comment by dreamMilk** [comment]
破案了，是我新开的分辨率没有调好，和脚本配置不符，所以没有点击铃铛🤣
还是感谢作者抽空解答👍
